### ISSUE TITLE
Importing old mnemonic in browser

### ISSUE THREAD

**Issue by ghost** [dashevo/js-dash-sdk#167] opened 2020-12-04 09:15 UTC
I cannot import my "old" mnemonic within Chrome Wallet in Chrome or Firefox since new dashjs 16.3 release. Import works with a newly generated mnemonic from dashjs 16.3 - but not with the old one.

Import will just freeze while executing `account = await sdk.getWalletAccount();` not giving an error or success (waited 20 min). Source line in CW: https://github.com/readme55/Dash-Chrome-Wallet/blob/master/app/background.js#L143

"old" Mnemonic: wealth recycle unit rocket milk defy alter just into inquiry universe cloth

I can import it within Node on command line.

**Comment by dashameter** [comment] 2021-08-31 12:25
@readme55 can you verify that this issue is still current on js-sdk v.20 or if it can be closed?

**Comment by SamKirby22** [comment] 2021-11-19 08:34
Closing as duplicate of https://github.com/dashevo/wallet-lib/issues/277#issue-936172688

**Closed by SamKirby22** 2021-11-19 08:34 UTC
Labels: bug
